services:
  - type: web
    name: my-flask-app
    env: python
    buildCommand: ""
    startCommand: gunicorn -w 4 -b 0.0.0.0:5000 backend.app:app
    envVars:
      - key: FLASK_ENV
        value: production
    regions:
      - oregon
